### ISSUE TITLE
date argument to javascript should always be passed in non-localized format.

### ISSUE THREAD

**Issue by AxTheB** [FlipperPA/django-tempus-dominus#3]
when I display form translated to czech language, it tries to display date in local datetime format (DD.MM.YYYY HH:mm:ss), but javascript does not parse it to any date, so the datetime field immediatelly blanks. Console shows warning (value provided is not in a recognized RFC2822 or ISO format). 

When I manually reformat the date argument to datetimepicker js to YYYY-MM-DD HH:mm:ss format it starts to work.

**Comment by AxTheB** [comment]
Which is not easily solvable, because after invalid form validation widget gets last displayed values as localised string and not datetime object. Real solution is probably passing parsing format to moment()

**Comment by FlipperPA** [comment]
@AxTheB Thanks to a PR, we are now passing in Moment's format... can you take a look at the most recent PR and see if that fixes your issue? Thank you!

**Comment by AxTheB** [comment]
Sorry I dont see any pull requests here. And I think the problem is in tempusdominus core, see https://github.com/tempusdominus/bootstrap-4/issues/182

**Comment by AxTheB** [comment]
Ah, I see it now: https://github.com/FlipperPA/django-tempus-dominus/pull/4
Its interesting, I will try it as soon as possible.

**Comment by AxTheB** [comment]
Yea, it looks like it works well. Thanks a lot.

**Comment by FlipperPA** [comment]
Thank to @ianastewart - he's the one who fixed it! Take care.
