### ISSUE TITLE
python to js serialization

### ISSUE THREAD

**Issue by frague59** [FlipperPA/django-tempus-dominus#34]
Hi, 

I've noticed an error on template rendering; The js_options data are not serialized into js object, and the boolean values appears as `True`, `False` and not `true` and `false`. I've done a work-around fixed it by adding:
```js
const True = true; 
const False = false;
```

But it should be better to json-serialize the options on render.

Thanks again !

**Comment by FlipperPA** [comment]
Howdy @frague59, were you using an older version of the package? I believe this was fixed in this P.R.: https://github.com/FlipperPA/django-tempus-dominus/pull/29

**Comment by frague59** [comment]
yep, it's fixed.
