### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by swaterfall** [FlipperPA/django-tempus-dominus#36]
Hey,

I've just added this to my Django project with basic setup and it's giving me a syntax error:

```
File "../forms.py", line 12, in <module>
    from tempus_dominus.widgets import DateTimePicker
  File "../python2.7/site-packages/tempus_dominus/widgets.py", line 46
    self.js_options = {**self.js_options, **options}
                      ^
SyntaxError: invalid syntax

```

Any Ideas? Guessing its only Python 3+?

**Comment by FlipperPA** [comment]
You are correct, we have targeted Python 3.5+ only, as Django no longer supports Python 2.7 in new versions (2.0+). This is the source of your problem:

https://stackoverflow.com/a/26853961/1394697

Are you planning on moving to Python 3 any time soon? We could consider using a dict merge function as described in the answer, but it seems very few people are still using Django on Python 2.7. Thanks for the report!
