### ISSUE TITLE
initial value for the widget 

### ISSUE THREAD

**Issue by frague59** [FlipperPA/django-tempus-dominus#37]
Hi, 
I've set an initial value to a TimePicker, it seems not to be rendered in the piker on the page: the `moment_option` method tries to format a date, not a time...

Thanks !

**Comment by frague59** [comment]
The time is passed to the widget, in a "date" attr: 
```js
    $(function () {
        $('#id_AUTH-auth_sound_system_start_at').datetimepicker({"format": "LT", "icons": {"time": "fa fa-clock"}, "stepping": 15, "useCurrent": false, "append": "fa fa-clock", "locale": "fr", "date": "08:00:00"});
    });
```

**Comment by ianastewart** [comment]
Hi,
The date attribute is the only option that can pass a value into the datepicker. I wrote the bit of code that initialises values but I could only get it to work for a date or datetime but not for a time. There is a comment to that effect in the code. I'll have another look at it, but it may be a restriction of the underlying tempus dominus library.
Ian

**Comment by ianastewart** [comment]
Ok, I see where this is going wrong. It is possible to pass a time to the widget through the date attribute but it has to be formatted as the last part of an iso date string e.g. "T12:30:00". There also needs to be a change in the html that the widget generates. The existing template does not match the examples on the  tempus dominus website but works for date and datetime but mysteriously, not time alone. I should be able to create a pull request that fixes all this by this weekend.

**Comment by ianastewart** [comment]
@frague59 
I have just merged a pull request that fixes this issue.
@FlipperPA Tim - I will leave you to bump the version and do the upload to pypy.

**Comment by FlipperPA** [comment]
Thank you both! I'll get a new version out today.
