### ISSUE TITLE
Passing datetime as option only initialized on server restart

### ISSUE THREAD

**Issue by coler-j** [FlipperPA/django-tempus-dominus#41]
In the following example, won't the minDate only be initialized when the server starts?

`(datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')`

So if I run this today 2019-01-24 it will result in 2019-01-25. But then tomorrow (unless server has been restarted) it will still be the same value?

```
datetime_field = forms.DateTimeField(
        widget=DateTimePicker(
            options={
                'minDate': (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d'),  # Tomorrow
                'useCurrent': True,
                'collapse': False,
            },
            attrs={
               'append': 'fa fa-calendar',
               'input_toggle': False,
               'icon_toggle': True,
            }
        ),
    )
```

**Comment by FlipperPA** [comment]
Excellent point, it would have to be done in the view. I'm removing it from the example.
