### ISSUE TITLE
Make containing <div class="input-group"> optional

### ISSUE THREAD

**Issue by rorosentrater** [FlipperPA/django-tempus-dominus#42]
The current widget template is thus:
```
<div class="input-group{% if size == 'small' %} input-group-sm{% elif size == 'large' %} input-group-lg{% endif %}"
  id="div_{{ picker_id }}" data-target-input="nearest">
  {% if prepend %}
    <div class="input-group-prepend" data-target="#{{ picker_id }}" {% if icon_toggle %}data-toggle="datetimepicker"{% endif %}>
      <div class="input-group-text"><i class="{{ prepend }}"></i></div>
    </div>
  {% endif %}
  <input type="{{ type }}" name="{{ name }}"{{ attrs }} {% if input_toggle %}data-toggle="datetimepicker"{% endif %}
         data-target="#{{ picker_id }}">
  {% if append %}
    <div class="input-group-append" data-target="#{{ picker_id }}" {% if icon_toggle %}data-toggle="datetimepicker"{% endif %}>
        <div class="input-group-text"><i class="{{ append }}"></i></div>
    </div>
  {% endif %}
</div>
<script type="text/javascript">
    $(function () {
        $('#{{ picker_id }}').datetimepicker({{ js_options }});
    });
</script>
```

On line 1 you can see there is no {% if x %} on the upper most container div. By default I think this is what most people want but there is no way with an options parameter for example, to disable the usage of this div. This is a problem if someone wanted to, for example, display multiple datepickers inline sort of like [this](https://getbootstrap.com/docs/4.0/components/input-group/#multiple-inputs) example shown in the bootstrap docs.

**Comment by rorosentrater** [comment]
I made my own jank fix for this. in widgets.py I added a "parent" variable to the render method with a default value of True (again, since I think most people actually do usually want the input-group by default) added another elif to the all_attrs.items() loop + an {% if %} on the appropriate part of the template and voila! There is now a new attrs key you can toggle called 'parent' you can use to toggle the use of the parent container. something like `DatePicker(attrs={'parent': False})`. Of course, now that there is no parent container it's up to you to add your own or the widget's JS will complain.

**Comment by FlipperPA** [comment]
I've made this in option in version 5.1.2.4, now available on PyPI.
