### ISSUE TITLE
'datetimepicker' is not a function

### ISSUE THREAD

**Issue by OrangyTang** [FlipperPA/django-tempus-dominus#45]
I'm not sure if what I'm seeing is a bug or a mistake on my part, but I'm getting the following error:

[TypeError: $(...).datetimepicker is not a function](url)

From the following generated html:

```
<div class="row">
	<form action="" method="post" class="graphConfig">		
		<ul>
			<input type="hidden" name="csrfmiddlewaretoken" value="aj2SpLuX4U3bzxNFfVarg6tKK0Y8qThhHkDrzYzHMSDWJUj83zHjVOE4Ngqv2fSq">
			<li><label for="id_your_name">Your name:</label> <input type="text" name="your_name" maxlength="100" required id="id_your_name"></li>
<li><label for="id_startDate">Startdate:</label> <div class="input-group"
  id="div_id_startDate" data-target-input="nearest">
  
  <input type="text" name="startDate" required="True" id="id_startDate" class="form-control  datetimepicker-input" data-toggle="datetimepicker"
         data-target="#id_startDate">
  
</div>
<script type="text/javascript">
    $(function () {
        $('#id_startDate').datetimepicker({"format": "%d.%m.%Y", "icons": {"time": "fa fa-clock"}, "minDate": "2019-02-02", "date": "2019-03-13"});
    });
</script>
</li>
			<input type="submit" value="Submit">
		</ul>
	</form>
</div>

```
I'm manually including jquery before the {{ form.media }} so all the scripts should be in the correct order, and using the embedded moment and bootstrap libs.

Everything seems to line up ok, but I'm not sure why the actual init function to pass in the params from the form is failing. Any ideas?

Thanks.

Django v2.7.1 final
Python 3.7.2
django-tempus-dominus 5.1.2.3
jquery 3.3.1

**Comment by FlipperPA** [comment]
Can you include the code from the entire HTML page so I can get a solid repro of the exact problem, @OrangyTang? Thanks!

**Comment by rorosentrater** [comment]
You made sure your jquery script came before {{ form.media }}, but where did you put your {{ form.media }} reference? It should be before any of your date inputs. Or more explicitly; before any of your scripts that call `$(...).datetimepicker`

**Comment by OrangyTang** [comment]
Hello!

Thanks for the hints guys. I went over it with fresh eyes and found a 3rd party include that was double-y including jquery (albeit the same version) and screwing up the initialisation order.

I'd be nice if this produced a more sane error, but I'm not sure if that's possible. Either way, it's working great now.

**Comment by m0nk-tnd** [comment]
Hello, there is patch for this project for split js with html.
With this patch you can use TEMPUS_DOMINUS_SPLIT_JS setting - it will remove js from widget html. Then you may use {{ form.fields.FIELD_NAME.widget.rendered_js }} to output js in needed place.

[add-split-js.patch.txt](https://github.com/FlipperPA/django-tempus-dominus/files/3119726/add-split-js.patch.txt)

**Comment by FlipperPA** [comment]
@m0nk-tnd Can you issue this as a PR? That'd be great, so it doesn't get buried in an issue. Thanks!
