### ISSUE TITLE
DateTime pickup not displaying on template extending

### ISSUE THREAD

**Issue by JeromeDesseaux** [FlipperPA/django-tempus-dominus#46]
Hi and thanks for this awesome work ! 

I'm trying to get your library working on my project but I'm facing a bug : 
I got a "base.html" template which is a simple html snippet loading all the requirements in the head : bootstrap & jquery following your documentation. 

I also created a simple block called "media" which is just after the calls to jquery and bootstrap's CDNs. 

Calling {{form.media}} inside the media block from my "form.html" template which extends base.html populates the DOM fine, but the datetimepicker dont show up. Moving {{form.media}} inside the <form> doesn't work neither. But, just outside the "content" block, it works. 

Another thing : I'm french, and using my locale the field wont validate. I have to remove my config to make it work. 

Thanks for looking at it :)

**Comment by FlipperPA** [comment]
Bonjour @JeromeDesseaux! Ça va? Je parle un peu de français.

Now that I've embarrassed myself, can you include the full code for the base template, and the template that inherits from it, so I can try to reproduce the issue? Blocks get tricky sometimes.
