### ISSUE TITLE
Is there a way to change date/time-format

### ISSUE THREAD

**Issue by knasti** [FlipperPA/django-tempus-dominus#49]
I've started using tempus dominus as a widget for my date, time and datetime widgets. I set TEMPUS_DOMINUS_LOCALIZE to True, which solved translation of the widget, however with the sideffect (which is also listed in the Readme) of picking up localized date and time formats. Is there an easy way to force a specific date or/and time format without losing the translation?

I tried to parse the format like the following, but it does not recognize the format:

`widget=forms.DateInput(attrs={'class':'datepicker form-control', 'placeholder':'Select a date'}), format='%d/%m/%Y')`

Also thanks for implementing this good looking date/timepicker widget into django.

**Comment by ianastewart** [comment]
You can set the input format, but you have to use the formats used by moment.js, a Javascript library that tempus-dominus uses. See [these docs](http://momentjs.com/docs/#/displaying/format/) for valid formats as referenced in the tempus-dominus documentation. You are using Python strftime format syntax which won't be recognised. Try something like this in your form:
`mydate = forms.DateField(widget=DatePicker(options={'format': 'DD/MM/YYYY'}))`
