### ISSUE TITLE
support django-csp

### ISSUE THREAD

**Issue by graingert** [FlipperPA/django-tempus-dominus#56]
remove inline js

**Comment by FlipperPA** [comment]
Sorry, I'm not sure what you're asking. Please provide enough details if there's something you need.

**Comment by graingert** [comment]
@FlipperPA this script will not run when using a secure CSP

https://github.com/FlipperPA/django-tempus-dominus/blob/master/tempus_dominus/templates/tempus_dominus/widget.html#L18

Inline JS should be moved into a static file, and templated variables in JS should use the https://docs.djangoproject.com/en/2.2/ref/templates/builtins/#json-script template tag and loaded with `document.getElementById`
