### ISSUE TITLE
Upgrading 5.1.2.5 -> 5.1.2.6 breaks the package with javascript errors

### ISSUE THREAD

**Issue by violuke** [FlipperPA/django-tempus-dominus#57]
Thanks firstly for creating and managing this package 👍 

The latest version with the deferred setup is broken for us.

We get the JS error:
`ReferenceError: deferDateTimePicker is not defined`

<img width="1853" alt="Screenshot 2019-09-07 at 10 33 25 am" src="https://user-images.githubusercontent.com/6420347/64472762-36046e80-d15b-11e9-9cc7-b880e3546d7c.png">

The error seems to have been introduced in https://github.com/FlipperPA/django-tempus-dominus/commit/1beedcdca02c2248f28bd283882f82f73d764be0#diff-3afbed890b18bbb9dac80f6a99316e5aR23. I'll submit a PR to fix it which we appreciate if you could review and release an updated version. Thanks.

**Comment by FlipperPA** [comment]
This has been fixed and published in version 5.1.2.7. Thank you!
