### ISSUE TITLE
Widget does not work properly with formsets (existing values are not displayed)

### ISSUE THREAD

**Issue by CountBigBang** [FlipperPA/django-tempus-dominus#59]
A javascript function containing the picker_id in its name is dynamically generated for each widget (widget.html, line 19).

In a formset, Django dynamically generates identifiers for each form in a formset in the format 'id_table-number-Field'. Thus, the picker_id contains a **hyphen** which must not be part of a function name in JavaScript. This causes an error when the page is loaded. The picker does not display an existing field value.

A simple solution would be to replace any hyphen in the picker_id by an underscore.

**Comment by FlipperPA** [comment]
Ah, good catch! Unfortunately, the tests didn't catch this, nor did my actual tests, as the `defer` didn't happen. Trying to figure out a good way to test this, but your solution seems good. I'll get it in place.

**Comment by FlipperPA** [comment]
This has been fixed and published in version 5.1.2.7. Thank you!
