### ISSUE TITLE
[Example] Rendering django-tempus-dominus in a MultiWidget

### ISSUE THREAD

**Issue by nlittlejohns** [FlipperPA/django-tempus-dominus#60]
Hi all,
When you try to put django-tempus-dominus in a Django MultiWidget, it just renders a regular field. This is because the default renderer for MultiWidget expects the variable template_name to be present in the widget to describe how to render the widget.

Because django-tempus-dominus's template is full of variables, I think rendering this might be tricky (though it's probably possible with more knowledge than I have). As a workaround, I wrote this MultiWidget with a custom render method which invokes django-tempus-dominus' render method. It's a little hacky, but pretty effective.

The use case for this is if you want to use a SplitDateTimeField in your Form. Use this custom widget as the widget for the form, and in your model use a regular DateTimeField.

Hope this helps someone because it took me hours to figure out! If anyone has suggestions on a better way to do it, I'm all ears.

For this to work, there's a small tweak needed in django-tempus-dominus' widgets.py to support lists of values:

```python
        if type(context["widget"]["value"]) is list:
            for value in context["widget"]["value"]:
                if value is not None:
                    options.update(self.moment_option(value))
        elif context["widget"]["value"] is not None:
            # Append an option to set the datepicker's value using a Javascript
            # moment object
            options.update(self.moment_option(value))
```
I'll submit this as a PR.

Here's the custom widget:
https://gist.github.com/nlittlejohns/748033df23a04f600801c8cfcc112c45

**Comment by nlittlejohns** [comment]
Oops, turns out there was a bug in my code which caused this issue, not a bug in django-tempus-dominus. I'll update my example now (still valid!)

**Comment by FlipperPA** [comment]
Thanks for the comment @nlittlejohns - are you saying that this does work properly with Django's MultiWidget after fixing that bug? If so, I still think this is a valid contribution, would you like to put it as an example in the README, or perhaps start an "examples" directory in the repository?

**Comment by nlittlejohns** [comment]
Yeah, the "fix" that I proposed is not necessary in order for django-tempus-dominus to work with multiwidgets.

The issue occurred because I was accidentally shoehorning the widget into a DateTimeField instead of a SplitDateTimeField. This happened because I was using FormSets and I thought the FormSet Factory was using my custom form, but it was in fact auto-generating a form with incorrect Field Types on the fly. Once I specified my Form (with a SplitDateTimeField) in the FormSet Factory, it worked properly.

It's a bit confusing that Django tries to force a list of values into a field instead of throwing an error, but there you go. Still my fault!


I've fixed most of my MultiWidget issues now. I was having trouble getting UpdateViews to correctly populate existing values, which I think is an issue with Tempus Dominus. When specifying an initial value for the SplitDateFields, you need to specify a Date or Time, not a DateTime, so you need to specify "myDateTime.date()" for the value to appear correctly.

The one thing that I haven't been able to get working at all is setting Initial values on a blank form when using a MultiWidget, but for now I'm just ignoring it.

I've updated my Gist a few times (including a few minutes ago) with an example customized SplitDateTimeWidget, which overall works pretty well. It extends SplitDateTimeWidget and replaces the widgets with django-tempus-dominus widgets. It also overrides the render method to make sure that django-tempus-dominus' render method is called (if you don't do this, it relies on template rendering). The render method also includes a workaround for the .date() or .time() issue.

https://gist.github.com/nlittlejohns/748033df23a04f600801c8cfcc112c45

**Comment by nlittlejohns** [comment]
It's probably a useful example since there's not much documentation out there for MultiWidgets. I'll make a PR to update the docs with the MultiWidget as an example. Hopefully it helps some people use multi widgets (which are really helpful once you get them working!)

**Comment by FlipperPA** [comment]
That would be great! Hopefully it'll save someone that pain point down the road. And don't forget to add yourself to the contributor list as well. Thanks!
