### ISSUE TITLE
Provides the hability to include tempusdominus js from local service

### ISSUE THREAD

**Issue by frague59** [FlipperPA/django-tempus-dominus#7]
Hi, 

It would be nice to add some settings to the app to use install tempus dominus locally with node, and avoid CDN, like done in https://github.com/tutorcruncher/django-bootstrap3-datetimepicker by example.

You could add a dependancie to django-appconf to provide settings...

Thanks !

**Comment by FlipperPA** [comment]
This feature has been included the latest release. Cheers!
