### ISSUE TITLE
NEXT GENERATION: What Date & Time Picker should we move to?

### ISSUE THREAD

**Issue by FlipperPA** [FlipperPA/django-tempus-dominus#70]
This one looks promising: https://amsul.ca/pickadate.js/

**Comment by FlipperPA** [comment]
https://www.jqueryscript.net/blog/best-date-time-picker.html

**Comment by FlipperPA** [comment]
Focus on accessibility: https://www.webaxe.org/accessible-date-pickers/

**Comment by nlittlejohns** [comment]
I spent a good chunk of time yesterday looking for a replacement for Tempus Dominus, and I didn't find anything that looked good, supported BS4 and seemed well-maintained.

Eventually, I came to the conclusion that it's time to give up on JS-based date pickers and instead rely on the date/time input types added in HTML5. This isn't such a good solution if you need to support legacy browsers, but all mobile browsers, plus Chrome and Firefox (and I think Edge?) on desktop all have built-in date/time pickers now. The one outlier seems to be Safari on macOS, which does nothing.

Desktop Safari is a pretty small number of users (though I am one of them!), so my plan is to pre-fill today's date on the form to show users the format, then if they're using anything other than desktop Safari, they'll get a picker, and if they're using desktop Safari, they'll at least see the date format pre-filled.

Django doesn't use the HTML date/time input types, but it's easy to add support for them. Here's a useful guide: https://djangotricks.blogspot.com/2019/10/working-with-dates-and-times-in-forms.html

**Comment by FlipperPA** [comment]
Thanks for the input, @nlittlejohns. You may be right.

This one was recommended by a Wagtail core team member: https://github.com/airbnb/react-dates

But it has a ReactJS payload...

**Comment by makayabou** [comment]
There is a new release for tempus dominus

**Comment by dwasyl** [comment]
@FlipperPA Since tempus has long moved to v6.x, and there's been no movement here, is it fair to assume there won't be any updates? I upgraded to `v..2.17` from `v...2.5` and have run into issues where it displays the wrong date (seems to shift all dates back one of two days). Just trying to decide if I should switch to html5 dates or manually add the latest tempus.
