### ISSUE TITLE
Including Locale to Django Package

### ISSUE THREAD

**Issue by adreyesr** [FlipperPA/django-tempus-dominus#71]
Hi, 

I have tried to set the option of locate (language change) without success, if that option available in this package?

**Comment by T-101** [comment]
in django settings you must have:
```TEMPUS_DOMINUS_LOCALIZE = True``` this will load a version of `moment.js` which support locales

and then in your forms:
```forms.DateTimeField(widget=DateTimePicker(options={'locale': 'en-ie'}))``` or whatever locale you need
