### ISSUE TITLE
Uncaught Error: Tempus Dominus Bootstrap4's requires jQuery. jQuery must be included before Tempus Dominus Bootstrap4's JavaScript.

### ISSUE THREAD

**Issue by b-ibragimov** [FlipperPA/django-tempus-dominus#79]
Uncaught Error: Tempus Dominus Bootstrap4's requires jQuery. jQuery must be included before Tempus Dominus Bootstrap4's JavaScript.

how to fix this

**Comment by FlipperPA** [comment]
In the `README`, [check out this section](https://github.com/FlipperPA/django-tempus-dominus#usage--django-settings):

If you scroll down to the example, it says, "Then in your template, include jQuery, `{{ form.media }}`, and render the form". do this and you should be good to go.
