### ISSUE TITLE
Documentation regarding template should be improved.

### ISSUE THREAD

**Issue by ianastewart** [FlipperPA/django-tempus-dominus#9]
The template that is shown does not work if simply copied verbatim.
Firstly, you should mention that bootstrap.css should be loaded, though that should be obvious.
Secondlt, please mention that font awesome is needed for the icons on the date picker to appear correctly.  I found that it does not show the clock icon correctly on the date and time picker when you use the latest version 5 of font awesome from the cdn.  It's best to stick to version 4.7, which is what is used in the tempus dominus demo pages. Maybe that fiel should be part of form.media.
And finally, unless you put the form inside a container, and a column (or more likely a container, row and column),  tempus-dominus will pause on an exception: "datetimepicker component should be placed within a relative positioned container". 
I have incorporated all of the above in the attached file.

[template.txt](https://github.com/FlipperPA/django-tempus-dominus/files/2420894/template.txt)

**Comment by FlipperPA** [comment]
Thank you again, @ianastewart - this has been updated with some code comments.

It'll go out with today's release.
